build:
  script:
    - pelican  content -o output -s pelicanconf.py
  artifacts:
    paths:
        - output
        
deploy:
  script:
  - git clone --depth 1 https://$GITHUB_USERNAME:$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_USERNAME.github.io.git public
  - git config user.email "$GITHUB_EMAIL"
  - git config --global user.name "$GITHUB_NAME"
  - git add -A
  - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
  - git push
  artifacts:
    paths:
    - public
  only:
  - master
  dependencies:
    - build