build:
  script:
    - pelican  content -o output -s pelicanconf.py
  artifacts:
    paths:
        - output
        
deploy:
  script:
  - git remote add origin -t $GH_PAGES_BRANCH https://x-access-token:$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO_NAME.git
  - git config --global user.email "$GITHUB_EMAIL"
  - git config --global user.name "$GITHUB_NAME"
  - git add -A
  - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
  - git push origin HEAD:$GH_PAGES_BRANCH
  only:
  - master
